# Generic Config
__version__ = "0.1.0"

# Config for the evolution simulator
IMAGE_SIZE = 28

NEW_CONFIG_RANGE = 0.1
STARTING_MUTATION_RATE = 0.05

NEURONS_PER_HIDDEN_LAYER = 16

NUM_HIDDEN_LAYERS = 2
POPULATION_SIZE = 20
NUM_GENERATIONS = 500

# Config for the GUI
FPS = 60
WN_W, WN_H = 1250, 750

